### PR TITLE
Add compatibility for loop inside JSX

### PR DESCRIPTION
**Pull request by f107**
I have added the compatibility with loop inside JSX, I hope it's okay

### CODE REVIEW

**Comment by bitboxer** [comment]
Oh sorry that I haven't replied earlier. Will look at it tonight.

**Comment by bitboxer** [comment]
So found some time between tickets and now it's merged. Thanks again for this.

I want to focus on this extension this month to make it really production ready. If you are using this and are interested in helping, we should talk :)

**Comment by bitboxer** [comment]
It is deployed now as `0.2.0` . And I re-enabled the issues part of this repo and already added two things. If you have other things that you want to see implemented, feel free to add them.

**Comment by f107** [comment]
> So found some time between tickets and now it's merged. Thanks again for this.
> 
> I want to focus on this extension this month to make it really production ready. If you are using this and are interested in helping, we should talk :)

thanks!
I also added other features (such as using functions as components, new method to add events ) and I used this module for my project (https://problemidelvento.it), 
I could share these updates with you if you want see them

**Comment by bitboxer** [comment]
Oh yes! Those are on my todo as well 😄

**Pull request merged**
