### PR TITLE
Add Object.entries Polyfill (#2)

### PR DESCRIPTION
**Pull request by f107**
Is something like that okay?

### CODE REVIEW

**Comment by bitboxer** [comment]
Thanks for this PR 🎉. This looks really nice, with one little caveat: the dist folder should contain only one JavaScript file that includes everything needed to use the library. Could you modify the `package.json` to do this?

**Comment by f107** [comment]
I have added Rollup for deployment process, thanks for the advice. Let me know :smiley:

**Comment by bitboxer** [comment]
Awesome. Looks really great. Merging now. Sadly I will go on vacation tomorrow and don't have time to do a proper release with this before. Will do when I am back.

**Comment by bitboxer** [comment]
This is now deployed as `0.5.0`. Thanks again for your contribution.

**Pull request merged**
