### PR TITLE
Add beforeend and afterend render options

### PR DESCRIPTION
**Pull request by theodugautier**
## Problem

I want to be able to render JSX elements but after the content of the parent and sometimes by replacing the content.

## Solutions

- Set up three functions to be able to render `afterend`, `beforeend` and by replacing contents on the parent element.
- Adding Jest tests.

### CODE REVIEW

**Comment by bitboxer** [comment]
Thank you for this fantastic PR. 

Can you add a little example to the README? Sadly there are no real API docs right now and if it's not in the readme, people won't find it.

Don't worry if you don't have time for that, I can take over from here if you prefer that.

**Comment by theodugautier** [comment]
No problem, I'll do it as soon as I have some time !

**Comment by theodugautier** [comment]
@bitboxer I added the documentation and a new function (I had made a helper in my personal app to do this but I think it's better that it's there) that allows to replace the content of the parent element.

**Review by bitboxer — APPROVED** [review]

**Comment by bitboxer** [comment]
Awesome. Thank you.

**Comment by bitboxer** [comment]
Version 1.1.0 with your changes is now released 🥳

**Pull request merged**
